version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo Installing Maven...
      - apt-get update -y
      - apt-get install -y maven
  build:
    commands:
      - echo Build started
      - mvn clean package
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - target/simple-spring-api-0.0.1-SNAPSHOT.jar